### PR TITLE
Fix README

### PR DESCRIPTION
**Pull request by camelpunch**

### CODE REVIEW

**Comment by zachgersh** [comment]
hey @camelpunch, would love to understand the reasoning here behind removing our gif from the repo.

**Comment by camelpunch** [comment]
It's driving me INSANE. But I understand if you just close this.

**Comment by zachgersh** [comment]
We'd always be open to another gif that features `om` like aesthetics. Please PR one but the repo has to have a gif of some sort.

**Comment by cholick** [comment]
Sad this PR wasn't accepted: the animated gif drives me crazy as well.

**Pull request closed without merging**
