### PR TITLE
Removed redundant commands in readme

### PR DESCRIPTION
**Pull request by jhmcstanton**
Looks like the bot was borked and repeatedly appended the commands to the readme. 

No idea where the bot is configured, so not sure what happened. Looks like maybe someone turned it off since it stopped committing this afternoon.

### CODE REVIEW

**Comment by jhmcstanton** [comment]
Readme broke the build D:

**Comment by jpmcb** [comment]
There was a network error. No worries, it is not an automatic rejection

**Comment by jpmcb** [comment]
Thanks for the catch, @jhmcstanton ! We found the culprit in our CI, and have fixed it so it doesn't happen again.

**Comment by kcboyle** [comment]
This bot existed in om/ci/tasks/readme/task.yml

We changed the commit name to be more helpful

**Pull request merged**
