### PR TITLE
Add vSphere IaaS configuration to bosh_form_models

### PR DESCRIPTION
**Pull request by sradnidge**
Adds the ability to target vSphere environments with `configure-bosh --iaas-configuration`

### CODE REVIEW

**Comment by zachgersh** [comment]
Hey @sradnidge thanks a lot for submitting this! Would you mind adding some tests around this?

There'd basically need to be at least an `iaas_configuration` section for vsphere in the acceptance level tests (I've pasted a link to the amazon one below).

https://github.com/pivotal-cf/om/blob/master/acceptance/configure_bosh_test.go#L314

**Comment by sradnidge** [comment]
Awesome, will do - thanks for pointing me there, I couldn't see anything provider specific in the _test.go and mistakenly assumed there were no tests :)

**Comment by zachgersh** [comment]
@sradnidge it is only testing for the fact that IAAS specific configuration doesn't appear if not set on the particular IAAS. So, a GCP field will never appear on an Azure IAAS specific configuration.

**Comment by sradnidge** [comment]
OK, thanks for the help Zach :), tests and docs added!

**Comment by zachgersh** [comment]
I merged this manually so I could squash the commits.

Thanks for this @sradnidge

**Comment by pivotal-issuemaster** [comment]
@sradnidge Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/om&pullRequestId=22)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/om&pullRequestId=22) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Pull request closed without merging**
