### PR TITLE
Officially Move `om` over to go modules

### PR DESCRIPTION
**Pull request by zachgersh**
The go world is changing and we are looking at a whole new world of dependency management (go modules) built directly into the go tool chain.

I've switched `om` over and in addition removed the `vendor` directory. This means you will need to tweak your build pipeline in one of two pretty simple ways:

1) if inside of the `GOPATH`: `GO111MODULE=on go build .`
2) if you want to build the project and not setup a `GOPATH`: `go build .`

### CODE REVIEW

**Comment by zachgersh** [comment]
Also, you are totally going to want to just look at the second commit and not the removes Gopkg commit - that thing is just removing a bunch of files :/

**Comment by jtarchie** [comment]
We might not be able to change yet. Will discuss via slack about the OSL process.

**Comment by jtarchie** [comment]
Have confirmed we can do this by OSL team.

To do list before fully supporting.

* [ ] need to migrate CI tasks to use `go mod` instead of `dep`
* [ ] local workflow changes, as we no longer use `GO_PATH` for this in development
* [ ] how does this affect our upstream dependency `p-automator`, which uses `dep` at the moment

**Comment by zachgersh** [comment]
I am going to fix this conflicting file! @jtarchie would it work better if we merged this to a particular transition branch so you can fix CI first? I can also take a look at p-automator to see what sort of changes would be required if you like.

**Comment by fredwangwang** [comment]
issue #277

**Comment by jtarchie** [comment]
Manually merged in.

Updating tasks to use it correctly.

**Pull request closed without merging**
