### PR TITLE
allow errand configuraiton during apply-changes 

### PR DESCRIPTION
**Pull request by fredwangwang**
Allows for errand configuration during apply changes via a configuration yaml file

Fixes https://github.com/pivotal-cf/om/issues/92

[https://www.pivotaltracker.com/story/show/161848001]

Signed-off-by: Huan Wang <huwang@pivotal.io>

### CODE REVIEW

**Comment by fredwangwang** [comment]
While doing it we also created a helper function called `fetchProductGUID()` to fetch product guid from both `staged-product` and `deployed-product`, since products that are staged for deletion are not shown up in `staged-product` endpoint.

This brings up a refactor opportunity to change all the guid fetching logic to use the helper function, since there is a edge case that `staged-product` does not contain the guid of the product. 

But we didn't spend the time doing it, as it didn't appears to a problem in the past and it does not affect the functionaility we added.

**Comment by kcboyle** [comment]
@fredwangwang @rheaton 
We are about to pull this in, but we've been testing it on the command line, and couldn't get the errands to skip. Is there something missing? using the format defined in the readme. 

We have the following config:
```
errands:
  cf:
    smoke_tests: false
    push-usage-service: false
    push-apps-manager: false
    deploy-notifications: false
    deploy-notifications-ui: false
    deploy-autoscaler: false
    test-autoscaling: false
    metric_registrar_smoke_test: false
    nfsbrokerpush: false
    smbbrokerpush: false
```

and run: `om --env env.yml apply-changes -c config.yml`, but we get output for each of the errands we thought we disabled. Is there a layer missing that just needs more documentation?

**Comment by fredwangwang** [comment]
that errands config format is wrong. Here is an example (its in the issue as well):
```
errands:
  product1_name:
    run_pre_delete:
      errand_a: true
      errand_b: false
    run_post_deploy:
      errand_c: "default"
  product2_name:
    run_post_deploy:
      errand_a: false
    run_pre_delete:
      errand_b: "default"
```

we dicided to go with this because it's the format used in the api docs directly: http://docs.pivotal.io/pivotalcf/2-3/opsman-api/#triggering-an-install-process

**Comment by kcboyle** [comment]
validated. Tested. merged.

**Pull request merged**
