### PR TITLE
added the target-config-file flag for om global settings

### PR DESCRIPTION
**Pull request by fredwangwang**
This is the PR related to issue https://github.com/pivotal-cf/om/issues/153

Signed-off-by: David Timm <dtimm@pivotal.io>

### CODE REVIEW

**Comment by ljfranklin** [comment]
@fredwangwang @jtarchie main slack convo is here: https://pivotal.slack.com/archives/C5V956L13/p1525794596000281. Copying my response from there:

RelEng here, looking at your PR: https://github.com/pivotal-cf/om/issues/153. I agree with Ryan here, I don't really want to merge that PR as I worry it encourages people to check secrets into version control rather than using more ephemeral creds from credhub/vault/whatever. As @zachgersh noted in the issue, you can work around this by checking in a script with a bunch of `export OM_PASSWORD...` lines in it, but our recommendation would be to not write creds to disk at all.

**Comment by ljfranklin** [comment]
@mcwumbly I'm leaning towards closing this without merging but I'd appreciate a sanity check from you. There's probably something we could be doing to better address credential management with `om` but encouraging writing creds to disk feels like a step in the wrong direction.

**Comment by aegershman** [comment]
Unsolicited, but for anyone reading this in need of ideas, what I like to do is keep my credentials files in a secure location outside the git repo entirely && I load them as env vars for the script to consume. For example, if I have some script called `myscript.sh`, I'd load in creds like this:

```bash
#!/bin/bash

# Declare needed variables. Or don't. Whatever. Your choice.
USERNAME=""
SECRET=""
TARGET=""
API_TOKEN=""
source ~/projects/credentials/myscript-creds-loader.sh

# code goes here blah blah blah
```

where `myscript-creds-loader.sh` looks like this:
```bash
#!/bin/bash
export USERNAME="actual-username"
export SECRET="actual-secret"
export TARGET="actual-value"
export API_TOKEN="actual-token"
```

Or instead of hardcoding them, you can have the `creds-loader.sh` load it from some external secure store:
```bash
export USERNAME=$(credhub get -n /concourse/mysecret --output-json | jq -r '.value.username')
export SECRET=$(credhub get -n /concourse/mysecret --output-json | jq -r '.value.password')
# etc etc
```

**Comment by jtarchie** [comment]
@ljfranklin and @zachgersh, are use case is that people would be getting these values and generating a temporary YAML file.

The argument of having a config file having credentials actively promotes checking may enable it, but doesn't actively enforce it. If we can provide mechanisms and good practices to our users, so they don't do that, that would be just as effective.

The counter-argument to that is the config file that can be provided already for `configure-director` and `config-product` can have credentials in them -- be they certs, SSH keys, etc. For example, the director config for `iaas-configuration` on GCP has the service account JSON it can set.

We can try to protect the user from themselves, but we know through experience, to quote famous mathematician and chaostician Ian Malcom, "Life will find a way."

If you would still like to close this. Maybe we can better articulate our use case, from a customer experience, to discuss further.

**Comment by mcwumbly** [comment]
We are going to pull this other PR into jhanda soon, and then bump it in `om`:

https://github.com/pivotal-cf/jhanda/pull/2

That should solve the immediate concern, as you can statefully set your environment.  For the other use cases being discussed here, we want to support templating variables (and secrets), a la: https://github.com/pivotal-cf/om/issues/140

So, closing this and the related issue for now.

**Pull request closed without merging**
