### PR TITLE
add support for HTTP/HTTPS Proxy and NoProxy when configuring authentication

### PR DESCRIPTION
**Pull request by rcw5**

### CODE REVIEW

**Comment by madamkiwi** [comment]
Thanks Robin!  We noticed that tests are failing (you may want to add `omitempty` to the new fields.  Could you also remove the short options, as we feel that the long options are sufficient.

Thanks again for the PR!

K & Andrew

**Comment by rcw5** [comment]
Thanks for the comments - have made the suggested changes and all tests are passing now.

**Comment by acrmp** [comment]
I've squashed the two commits and pushed this as 004557cd. Thanks!

Some versions of Pivotal Cloud Foundry Operations Manager do not allow the proxy to be configured through the API. Known recent versions that do support this at time of writing are:

* v1.9.17
* v1.10.12
* v1.11.6

**Comment by ljfranklin** [comment]
@rcw5 we're doing an audit to ensure all contributions are covered under the Pivotal Contributor License Agreement. Could you sign the CLA as described [here](https://cla.pivotal.io)? Thank you!

**Comment by pivotal-issuemaster** [comment]
@rcw5 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/om&pullRequestId=93)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/om&pullRequestId=93) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rcw5 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/om&pullRequestId=93)!

**Pull request closed without merging**
