### PR TITLE
WIP: Creating CI for the repository

### PR DESCRIPTION
**Pull request by jaristiz**
## What's new?

- Added CI for the repository.
    - On PR: `CI`, and `OM container CI`
    - On merge to `main`: `OM Container CD` --> Not tested
    - On New tag: `Release` --> Needs work
- Refactored `download_product_s3` acceptance tests to use variables.

### CODE REVIEW

**Comment by ciriarte** [comment]
@jaristiz why do we have so many workflows?

**Comment by jaristiz** [comment]
Was thinking on having 2 CI (App and Container) and 2 CD, feel free to remove/simplify, the one that is gailing is the CI one.

**Comment by ciriarte** [comment]
Thank you! I'll take a stab.

**Comment by jtarchie** [comment]
Is this a move away from concourse?

**Comment by jaristiz** [comment]
> Is this a move away from concourse?

Yes, the idea is to have the CI closer to the code, allowing us to test the code early.

**Comment by wayneadams** [comment]
Closed due to staleness

**Pull request closed without merging**
