### PR TITLE
Change generated placeholder names from periods to underscores in `config-template`

### PR DESCRIPTION
**Pull request by kcboyle**
This is done to match patterns seen around various cloud foundry projects
Signed-off-by: Huan Wang <huwang@pivotal.io>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kcboyle Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/om&pullRequestId=209)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/om&pullRequestId=209) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kcboyle Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/om&pullRequestId=209)!

**Comment by chendrix** [comment]
Some background on this for those coming in late. I changed the name of the Issue to I think better reflect the changes.

This would fix #189 

It's not a change to the config schema, but rather a change to the generated placeholder parameter names when running `config-template --include-placeholders`

**Comment by chendrix** [comment]
The underlying issue is that in #169, we added the support for `--include-placeholder` to the `staged-config` and `config-template` commands (https://github.com/pivotal-cf/om/commit/7d0cf8140f7a5f7aa9b94a2bf6ffc689a484e124). The naming scheme of the generated placeholders started off by being `((.properties.some-property.value))`. 

Then later in #181 this got changed to `((properties_some-property.value))`, but *only* for the `staged-config` command. There was a discrepancy that existed after that got fixed where `config-template` was still generating them using the other format.

I asked @kcboyle to add to this PR by making the two dependent on the same "PlaceholderGenerating" logic.

**Comment by kcboyle** [comment]
Closing as we do additional work

**Pull request closed without merging**
