### PR TITLE
Decorates collections with previous guid value

### PR DESCRIPTION
**Pull request by calebwashburn**
For issue 207 - https://github.com/pivotal-cf/om/issues/207 this PR will ensure previously configured items in collections are not replaced with new guid but instead will decorate the input with a guid if the same element has already been configured.

### CODE REVIEW

**Comment by calebwashburn** [comment]
@jtarchie Let me know if there is anything needed to get this merged.  This is causing issues where collections appear to change as guids are being modified forcing bosh to think it needs to update things.

```
Using deployment 'cf-5e2cea6ba2d14fbec849'

 addons:
 - name: ncp
   properties:
     ncp:
       nsx_v3:
         container_ip_blocks:
         - name: "<redacted>"
-           guid: "<redacted>"
+           guid: "<redacted>"
         external_ip_pools:
         - name: "<redacted>"
-           guid: "<redacted>"
+           guid: "<redacted>"
 
 instance_groups:
 - name: control
   jobs:
   - name: push-apps-manager
     properties:
       apps_manager:
         white_labeling:
           nav_links:
           - name: "<redacted>"
-             guid: "<redacted>"
+             guid: "<redacted>"
           - name: "<redacted>"
-             guid: "<redacted>"
+             guid: "<redacted>"
           - name: "<redacted>"
-             guid: "<redacted>"
+             guid: "<redacted>"

```

**Comment by calebwashburn** [comment]
Here's example how to test this with collection in PAS tile. 

https://gist.github.com/calebwashburn/771d75e6d22c121d622fc0f0041a31a4

Pre-merge there will be differences, post merge no differences

**Comment by jtarchie** [comment]
LGTM! When we use your example before and after, we no longer see the diff.

Because of the rebasing and merges, we manually pulled in this commit. It is still credited to you.

**Comment by jtarchie** [comment]
Manually merged on d61ff351a1d662068cdccb7aeaa1659ae0692877

**Pull request closed without merging**
