### PR TITLE
Adds a more bountiful yml file for an example.

### PR DESCRIPTION
**Pull request by voor**
Replaces the somewhat vague and cryptic yml example with one retrieved from `om --env env.yml staged-director-config --include-placeholders`

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@voor Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/om&pullRequestId=279)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cf/om&pullRequestId=279) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@voor Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cf/om&pullRequestId=279)!

**Comment by jtarchie** [comment]
Thanks @voor. We might wait on this at the moment. This is an example of just for AWS configuration. 

It was intentionally left vague at the moment until we figured a more consistent set of examples. For IAASes.

**Comment by fredwangwang** [comment]
Not only is this PR IaaS-specific, but also potentially version-specific. I don't think `om` is the proper place to maintain these bountiful example configuration files. However, if there is a place you know of that might be more suitable, we are more than happy to link to that place.

**Comment by voor** [comment]
It might make more sense to put these examples, or even call them out, in the terraform repositories

**Pull request closed without merging**
