### PR TITLE
adding operations file support to interpolate

### PR DESCRIPTION
**Pull request by calebwashburn**
- configure-product 
- configure-director

Will also support taking in yaml operations (patch) files.

### CODE REVIEW

**Comment by zachgersh** [comment]
Why are there no tests for this? Also, why is interpolate complete untested?

**Comment by calebwashburn** [comment]
@zachgersh Not sure why there are no tests.  I will update the PR with tests for the interpolate

**Comment by jtarchie** [comment]
@zachgersh: The tests for interpolate are [here](https://github.com/pivotal-cf/om/blob/master/acceptance/interpolate_test.go). It was so simple, doing the unit test seemed redundant at the time.

**Comment by calebwashburn** [comment]
@zachgersh Just checking in to see if any additional information is needed for this PR?

**Comment by ljfranklin** [comment]
@calebwashburn sorry for the delay on this. At a quick glance the code and tests look good to me.

@mcwumbly any product concerns around merging this in?

**Comment by mcwumbly** [comment]
> any product concerns around merging this in?

nope, if you're happy, i'm happy

**Pull request merged**
